# Generated by Django 4.2.1 on 2023-06-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_alter_suggestion_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
