# Generated by Django 4.2.1 on 2023-05-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='releaseset_date',
            new_name='release_date',
        ),
    ]
