# Generated by Django 4.2.1 on 2023-07-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_last_updated_movie_rating_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='idx',
            field=models.IntegerField(blank=True, help_text='continuous position for ml', null=True),
        ),
    ]
